version: '2'

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"

  # Our Redis service:
  redis:
    image: redis:latest
    ports:
      # We'll bind our host's port 6379 to redis's port 6379, so we can use
      # Redis Desktop Manager (or other tools) with it:
      - 6379:6379
    command: redis-server

  # Our ES service:
  elasticsearch:
    image: elasticsearch:latest
    ports:
      # We'll bind our host's port 6379 to redis's port 6379, so we can use
      # Redis Desktop Manager (or other tools) with it:
      - 9200:9200
    command: elasticsearch

  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    ports:
      - "3000:3000"
    links:
      - db
      - redis
      - elasticsearch
    volumes:
      - .:/myapp
    environment:
       - DOCKERIZED=true
