version: '2'

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"

  # Our Redis service:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    command: redis-server

  # Our ES service:
  elasticsearch:
    image: elasticsearch:latest
    ports:
      - "9200:9200"
    command: elasticsearch

  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: sidekiq -C config/sidekiq.yml
    env_file:
      - '.env'

  cable:
    depends_on:
      - 'redis'
    build: .
    command: puma -p 28080 cable/config.ru
    ports:
      - '28080:28080'
    env_file:
      - '.env'

  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    ports:
      - "3000:3000"
    depends_on:
      - 'db'
      - 'redis'
      - 'elasticsearch'
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/myapp
    environment:
      - DOCKERIZED=true
    env_file:
      - '.env'
