development:
    host: 'localhost'
    port: '6379'
#  namespace: appname_dev
test:
  db: 1
#  namespace: appname_test
production:
  host: 'hannah-co.nzpac7.0001.use1.cache.amazonaws.com'
  port: '6379'
#  namespace: appname_prod
