update_feed_entries_job:
  cron: "*/5 * * * *"
  class: "FeedEntryCronWorker"
  queue: default

update_feed_images_job:
  cron: "*/5 * * * *"
  class: "FeedImageCronWorker"
  queue: default_images

update_feed_cover_job:
  cron: "*/30 * * * *"
  class: "FeedCoverImageCronWorker"
  queue: default

update_counter_cache_job:
  cron: "0 0 * * * *"
  class: "CounterCacheCronWorker"
  queue: default
