# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: ded098c7922ed5b8ee1f8490c64c3a05162ff6b751894828c3dbc6c27e76ef8ebee1355c69974183c835922264208a54d3d08b349bf25f01a06e50a9a4a9eb92

test:
  domain_name: example.com 
  secret_key_base: d1a49cd9bda353214b005195deed1c424492786e9a9aed38eafac3d7a1670d64a2c0150ae57697edf017bf54744781bdcae73486ee24d779d4d1f40e88b6a89f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
