:concurrency: 5
:logfile: ./log/sidekiq.log
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - default
  - ahoy
  - emails
  - mailers
  - searchkick
  - default_images
:timeout: 400
